#@host = http://localhost/netflix
@host = http://netflix.cristiancarrino.com

### login

POST {{host}}/user/login.php HTTP/1.1
Content-Type: application/json

{
  "username": "stefy",
  "password": "5t3fan1a"
}

### edit user

POST {{host}}/user/edit.php HTTP/1.1
Content-Type: application/json
#NB: I campi username e password sono obbligatori.
#    Invece i campi newFirstname, newLastname, newUsername, newPassword
#    sono facoltativi ma ce ne deve essere almeno uno

{
  "username": "stef",
  "password": "stef",
  "newFirstname": "Stefania",
  "newLastname": "Cappellino",
  "newUsername": "stefy",
  "newPassword": "5t3fan1a"
}

### film list

GET {{host}}/film/read.php HTTP/1.1
Content-Type: application/json

### add film

POST {{host}}/film/create.php HTTP/1.1
Content-Type: application/json
Authorization: 7b5d6e52de7719d9

{
  "title": "Riverdale",
  "description": "La serie è incentrata su un mistero da risolvere, con i principali protagonisti 4 ragazzi",
  "director": "Lee Toland Krieger",
  "duration": "1:00",
  "releaseYear": 2017,
  "stars": 4,
  "cast": [
    {
      "firstname": "KJ",
      "lastname": "Apa"
    },
    {
      "firstname": "Lili",
      "lastname": "Reinhart"
    },
     {
      "firstname": "Camila",
      "lastname": "Mendes"
    },
     {
      "firstname": "Cole",
      "lastname": "Sprouse"
    }
  ],
  "genres": [
    {
      "name": "teen drama"
    },
    {
      "name": "thriller"
    },
     {
      "name": "crime"
    },
  ],
  "tags": "thriller, crime",
  "coverUrl": "https://movieplayer.net-cdn.it/t/images/2018/10/20/riverdale_jpg_375x0_crop_q85.jpg"
}

### edit film

POST {{host}}/film/update.php HTTP/1.1
Content-Type: application/json
Authorization: f0d7a79c2ccb2dbc

{
  "id": 35,
  "title": "Angeli e demoni",
  "description": "Robert Langdon, scopre alcune prove su un'antica società segreta che vuole distruggere la Chiesa cattolica",
  "director": "Ron Howard",
  "duration": "2:26",
  "releaseYear": 2009,
  "stars": 4,
  "cast": [
    {
      "firstname": "Tom",
      "lastname": "Hanks"
    }
  ],
  "genres": [
    {
      "name": "thriller"
    },
    {
      "name": "Azione"
    }
  ],
  "tags": "thriller, azione",
  "coverUrl": "https://www.italyformovies.it/media/img/oggetto_film/angeli_e_demoni_locandina_1546942592.jpg"
}

### remove film

POST {{host}}/film/delete.php HTTP/1.1
Content-Type: application/json
Authorization: f0d7a79c2ccb2dbc

{
  "id": 35
}

### actor list

GET {{host}}/actor/read.php HTTP/1.1
Content-Type: application/json

### actor add

POST {{host}}/actor/create.php HTTP/1.1
Content-Type: application/json
Authorization: f878c7c765643b37

{
  "firstname": "Paolo",
  "lastname": "Villaggio"
}

### actor edit

POST {{host}}/actor/update.php HTTP/1.1
Content-Type: application/json
Authorization: f878c7c765643b37

{
  "id": 3,
  "firstname": "Christian",
  "lastname": "De Sica"
}

### actor remove

POST {{host}}/actor/delete.php HTTP/1.1
Content-Type: application/json
Authorization: f878c7c765643b37

{
  "id": 2
}

### genre list

GET {{host}}/genre/read.php HTTP/1.1
Content-Type: application/json

### genre add

POST {{host}}/genre/create.php HTTP/1.1
Content-Type: application/json
Authorization: f878c7c765643b37

{
  "name": "Romantici"
}

### genre edit

POST {{host}}/genre/update.php HTTP/1.1
Content-Type: application/json
Authorization: f878c7c765643b37

{
  "id": 3,
  "name": "Horror"
}

### genre remove

POST {{host}}/genre/delete.php HTTP/1.1
Content-Type: application/json
Authorization: f878c7c765643b37

{
  "id": 4
}
